[I 2025-03-21 15:28:31,035] A new study created in memory with name: no-name-44808686-05b0-45b5-95e8-ebe219fcfcab
--- TS-CV Fold 1/2 ---
Use CPU
train 1889
val 1
test 192
[W 2025-03-21 15:28:31,093] Trial 0 failed with parameters: {'d_model': 1024, 'n_heads': 12, 'e_layers': 4, 'd_layers': 3, 'd_ff': 2560, 'dropout': 0.30497165881878574, 'batch_size': 64, 'activation': 'relu'} because of the following error: RuntimeError('mat1 and mat2 shapes cannot be multiplied (64x2070 and 1710x128)').
Traceback (most recent call last):
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/Users/choeseoheon/Desktop/Causal-Discovery/src/train/optuna.py", line 128, in objective
    val_loss = self._run_trial(args)
  File "/Users/choeseoheon/Desktop/Causal-Discovery/src/train/optuna.py", line 94, in _run_trial
    fold_loss = self._train_and_evaluate(fold_args, setting=f"trial_fold_{fold_id}")
  File "/Users/choeseoheon/Desktop/Causal-Discovery/src/train/optuna.py", line 63, in _train_and_evaluate
    trainer_initial.train(setting=setting)
  File "/Users/choeseoheon/Desktop/Causal-Discovery/src/train/exp_rnn.py", line 156, in train
    outputs = self.model(batch_x)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/choeseoheon/Desktop/Causal-Discovery/src/model/MLP.py", line 53, in forward
    h = self.layers(x)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/torch/nn/modules/container.py", line 250, in forward
    input = module(input)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 125, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (64x2070 and 1710x128)
[W 2025-03-21 15:28:31,095] Trial 0 failed with value None.
Traceback (most recent call last):
  File "/Users/choeseoheon/Desktop/Causal-Discovery/main.py", line 120, in <module>
    run(base_config)
  File "/Users/choeseoheon/Desktop/Causal-Discovery/main.py", line 111, in run
    tuner.run_study()
  File "/Users/choeseoheon/Desktop/Causal-Discovery/src/train/optuna.py", line 136, in run_study
    study.optimize(self.objective, n_trials=self.n_trials)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/Users/choeseoheon/Desktop/Causal-Discovery/src/train/optuna.py", line 128, in objective
    val_loss = self._run_trial(args)
  File "/Users/choeseoheon/Desktop/Causal-Discovery/src/train/optuna.py", line 94, in _run_trial
    fold_loss = self._train_and_evaluate(fold_args, setting=f"trial_fold_{fold_id}")
  File "/Users/choeseoheon/Desktop/Causal-Discovery/src/train/optuna.py", line 63, in _train_and_evaluate
    trainer_initial.train(setting=setting)
  File "/Users/choeseoheon/Desktop/Causal-Discovery/src/train/exp_rnn.py", line 156, in train
    outputs = self.model(batch_x)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/choeseoheon/Desktop/Causal-Discovery/src/model/MLP.py", line 53, in forward
    h = self.layers(x)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/torch/nn/modules/container.py", line 250, in forward
    input = module(input)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 125, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (64x2070 and 1710x128)
Traceback (most recent call last):
  File "/Users/choeseoheon/Desktop/Causal-Discovery/main.py", line 120, in <module>
    run(base_config)
  File "/Users/choeseoheon/Desktop/Causal-Discovery/main.py", line 111, in run
    tuner.run_study()
  File "/Users/choeseoheon/Desktop/Causal-Discovery/src/train/optuna.py", line 136, in run_study
    study.optimize(self.objective, n_trials=self.n_trials)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/Users/choeseoheon/Desktop/Causal-Discovery/src/train/optuna.py", line 128, in objective
    val_loss = self._run_trial(args)
  File "/Users/choeseoheon/Desktop/Causal-Discovery/src/train/optuna.py", line 94, in _run_trial
    fold_loss = self._train_and_evaluate(fold_args, setting=f"trial_fold_{fold_id}")
  File "/Users/choeseoheon/Desktop/Causal-Discovery/src/train/optuna.py", line 63, in _train_and_evaluate
    trainer_initial.train(setting=setting)
  File "/Users/choeseoheon/Desktop/Causal-Discovery/src/train/exp_rnn.py", line 156, in train
    outputs = self.model(batch_x)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/choeseoheon/Desktop/Causal-Discovery/src/model/MLP.py", line 53, in forward
    h = self.layers(x)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/torch/nn/modules/container.py", line 250, in forward
    input = module(input)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/capstone/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 125, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (64x2070 and 1710x128)
